//! Configuration management for verilib structure.

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

/// Configuration stored in .verilib/config.json
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Config {
    #[serde(rename = "structure-root")]
    pub structure_root: String,
}

/// Computed paths derived from config
#[derive(Debug, Clone)]
pub struct ConfigPaths {
    pub config: Config,
    pub verilib_path: PathBuf,
    pub structure_root: PathBuf,
    pub structure_json_path: PathBuf,
    pub atoms_path: PathBuf,
    pub certs_specify_dir: PathBuf,
    pub certs_verify_dir: PathBuf,
}

impl Config {
    /// Create a new config with the given parameters
    pub fn new(root: &str) -> Self {
        Self {
            structure_root: root.to_string(),
        }
    }

    /// Save config to .verilib/config.json
    pub fn save(&self, project_root: &Path) -> Result<PathBuf> {
        let verilib_path = project_root.join(".verilib");
        std::fs::create_dir_all(&verilib_path)
            .context("Failed to create .verilib directory")?;

        // Create .gitignore for generated files
        let gitignore_path = verilib_path.join(".gitignore");
        if !gitignore_path.exists() {
            let gitignore_content = "# Generated by VeriLib (not tracked)\natoms.json\nspecs.json\nstubs.json\nproofs.json\n";
            std::fs::write(&gitignore_path, gitignore_content)
                .context("Failed to write .gitignore")?;
        }

        let config_path = verilib_path.join("config.json");
        let content = serde_json::to_string_pretty(self)
            .context("Failed to serialize config")?;

        std::fs::write(&config_path, content)
            .context("Failed to write config.json")?;

        Ok(config_path)
    }
}

impl ConfigPaths {
    /// Load config and compute all paths
    pub fn load(project_root: &Path) -> Result<Self> {
        let verilib_path = project_root.join(".verilib");
        let config_path = verilib_path.join("config.json");

        if !config_path.exists() {
            anyhow::bail!(
                "{} not found. Run 'verilib-structure create' first.",
                config_path.display()
            );
        }

        let content = std::fs::read_to_string(&config_path)
            .context("Failed to read config.json")?;

        let config: Config = serde_json::from_str(&content)
            .context("Failed to parse config.json")?;

        let structure_root = project_root.join(&config.structure_root);

        Ok(Self {
            config,
            structure_root,
            structure_json_path: verilib_path.join("stubs.json"),
            atoms_path: verilib_path.join("atoms.json"),
            certs_specify_dir: verilib_path.join("certs").join("specify"),
            certs_verify_dir: verilib_path.join("certs").join("verify"),
            verilib_path,
        })
    }
}

/// Constants used throughout the application
pub mod constants {
    /// Repository for probe-verus installation instructions
    pub const PROBE_VERUS_REPO: &str = "https://github.com/Beneficial-AI-Foundation/probe-verus";

    /// Probe prefix for filtering atoms
    pub const PROBE_PREFIX: &str = "curve25519-dalek";
}
