//! probe-verus integration utilities.
//!
//! Handles interaction with the probe-verus CLI tool.

use anyhow::{bail, Result};
use std::path::Path;

/// Repository URL for probe-verus installation instructions.
pub const REPO_URL: &str = "https://github.com/Beneficial-AI-Foundation/probe-verus";

/// Default prefix for filtering probe atoms.
pub const DEFAULT_PREFIX: &str = "curve25519-dalek";

/// Check if probe-verus is installed and bail with instructions if not.
pub fn require_installed() -> Result<()> {
    if which::which("probe-verus").is_err() {
        eprintln!("Error: probe-verus is not installed.");
        eprintln!("Please visit {} for installation instructions.", REPO_URL);
        eprintln!();
        eprintln!("Quick install:");
        eprintln!("  git clone {}", REPO_URL);
        eprintln!("  cd probe-verus");
        eprintln!("  cargo install --path .");
        bail!("probe-verus not installed");
    }
    Ok(())
}

/// Clean up generated intermediate files from probe-verus commands.
///
/// Removes common intermediate files and the data directory if empty.
pub fn cleanup_intermediate_files(project_root: &Path, files: &[&str]) {
    for file in files {
        let path = project_root.join(file);
        if path.exists() {
            let _ = std::fs::remove_file(&path);
        }
    }

    // Remove data directory if empty
    let data_dir = project_root.join("data");
    if data_dir.exists() && data_dir.is_dir() {
        if let Ok(mut entries) = std::fs::read_dir(&data_dir) {
            if entries.next().is_none() {
                let _ = std::fs::remove_dir(&data_dir);
            }
        }
    }
}

/// Common intermediate files generated by atomize command.
pub const ATOMIZE_INTERMEDIATE_FILES: &[&str] = &["data/index.scip", "data/index.scip.json"];

/// Common intermediate files generated by verify command.
pub const VERIFY_INTERMEDIATE_FILES: &[&str] =
    &["data/verification_config.json", "data/verification_output.txt"];
